include_recipe 'test::run-psgi-app'
include_recipe 'test::install-catalyst-app'
include_recipe 'test::install-for-dancer'
include_recipe 'test::install-with-default-params'
include_recipe 'test::nginx'