#!/bin/sh
# chkconfig: 345 80 20
# description: <%= @daemon_name %> daemon

APPLICATION_USER=<%= @application_user %>
APPLICATION_HOME=<%= @application_home %>

<%- unless @perl5lib.empty? %>
PERL5LIB="<%= @perl5lib.join(':') %>"
<%- end %>

NAME="<%= @daemon_name %>"
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="<%= @application_desc %>"
DAEMON="<%= @daemon_path %>"
PIDFILE=/var/run/$NAME.pid

<%- if ! @proc_manager.nil? && ! @proc_manager.empty? %>
PROCMANAGER_OPT="--manager <%= @proc_manager %>"
<%- else %>
PROCMANAGER_OPT=""
<%- end %>

<%- if ! @proc_title.nil? && ! @proc_title.empty? %>
PROCTITLE_OPT="--proc_title <%= @proc_title %>"
<%- else %>
PROCTITLE_OPT=""
<%- end %>


<%- if ! @nproc.nil? && @server == 'FCGI' %>
NPROC_OPT="--nproc <%= @nproc %>"
<%- elsif ! @nproc.nil? && @server == 'Starman' %>
NPROC_OPT="--workers <%= @nproc %>"
<%- else %>
NPROC_OPT=""
<%- end %>

<%- if ! @mount.nil? && ! @mount.empty? %>
MOUNT_OPT="-e 'my \$app = do \"<%= @application_script %>\"; mount \"<%= @mount %>\" => \$app' "
<%- else %>
MOUNT_OPT=""
<%- end %>

DAEMON_ARGS="-s <%= @server %> $PROCMANAGER_OPT --listen <%= @socket %> -E <%= @plackup_environment %> $PROCTITLE_OPT $NPROC_OPT $MOUNT_OPT"

PIDFILE=/var/run/$NAME.pid

SCRIPTNAME=<%= @install_dir %>/$NAME

<%- vars = [] %>
<%- @envvars.each do |k,v| %>
    <%- vars << "#{k}=#{v}" %>
<%- end %>
ENVVARS='<%= vars.join(" ") %>'

. /etc/init.d/functions

start() {
	echo -n Starting <%= @daemon_name %>:
    eval "$ENVVARS" \
    <%- if @server == 'Twiggy' %>
    TWIGGY_DEBUG=<%= @debug %>
    <%- end %>

    <%- if @operator == 'Catalyst' %>
    CATALYST_CONFIG=<%= @config %>  CATALYST_DEBUG=<%= @debug %> \
    <%- elsif @operator == 'Dancer' %>
    DANCER_CONFDIR="${APPLICATION_HOME}" \
    <%- elsif @operator == 'Jifty' %>
    JIFTY_CONFIG="<%= @config %>" \
    <%- end %>
    <%- unless @perl5lib.empty? %>
    PERL5LIB="${PERL5LIB}" \
    <%- end %>
    cd $APPLICATION_HOME && daemon --pidfile $PIDFILE $DAEMON --user $APPLICATION_USER $DAEMON $DAEMON_ARGS
	retval=$?
	echo
	[ "$retval" = 0 ] && touch /var/lock/subsys/<%= @daemon_name %>
	return $retval
}

stop() {
	echo -n Stopping <%= @daemon_name %> server:
	killproc -p $PIDFILE $NAME
	retval=$?
	echo
	[ "$retval" = 0 ] && rm -f /var/lock/subsys/<%= @daemon_name %>
	return $retval
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	status)
		status -p $PIDFILE $NAME
		;;
	restart)
		stop
		start
		;;
	*)
		echo "Usage: <%= @daemon_name %> {start|stop|status|restart}"
		exit 1
		;;
esac

exit 0
